#!/usr/bin/env zsh

if [[ ${ZSH_SVN} -eq 0 ]] then
    svn_status="$(svn status -u 2>/dev/null || svn status 2>/dev/null)"
    svn_info="$(svn info)"

    export ZSH_SVN_INFO_DIRTY="$(svn_parse_dirty $svn_status)"
    export ZSH_SVN_INFO_BRANCH="$ZSH_THEME_SCM_BRANCH_PREFIX$(svn_parse_current_branch $svn_info)$ZSH_THEME_SCM_BRANCH_SUFFIX"
    export ZSH_SVN_INFO_BRANCH_STATUS="$(svn_parse_branch_status $svn_status)"
    export ZSH_SVN_INFO_PATCHES=""
    export ZSH_SVN_INFO_TAGS=""
fi
