#!/usr/bin/env zsh

if [[ ${ZSH_VCS_GIT_ON} -eq 0 ]] then
    git_branch="$(git branch -v 2>/dev/null | grep "^*")"
    git_status="$(git status --porcelain 2>/dev/null)"
    git_basedir="$(git rev-parse --show-toplevel 2>/dev/null)"

    export ZSH_GIT_INFO_DIRTY="$(git_parse_dirty $git_status $git_basedir)"
    export ZSH_GIT_INFO_BRANCH="$ZSH_THEME_SCM_BRANCH_PREFIX$(git_parse_current_branch $git_branch $git_basedir)$ZSH_THEME_SCM_BRANCH_SUFFIX"
    export ZSH_GIT_INFO_BRANCH_STATUS="$(git_parse_branch_status $git_branch $git_basedir)"
    export ZSH_GIT_INFO_PATCHES=""
    export ZSH_GIT_INFO_TAGS=""
fi
