#!/usr/bin/env zsh

local git_status=$1

STATUS=""

if $(echo "$git_status" | grep -q '^?? '); then
    STATUS="$ZSH_THEME_SCM_PROMPT_UNTRACKED$STATUS"
fi

if $(echo "$git_status" | grep -q '^A  '); then
    STATUS="$ZSH_THEME_SCM_PROMPT_ADDED$STATUS"
elif $(echo "$git_status" | grep -q '^M  '); then
    STATUS="$ZSH_THEME_SCM_PROMPT_ADDED$STATUS"
fi

if $(echo "$git_status" | grep -q '^ M '); then
    STATUS="$ZSH_THEME_SCM_PROMPT_MODIFIED$STATUS"
fi

if $(echo "$git_status" | grep -q '^R  '); then
    STATUS="$ZSH_THEME_SCM_PROMPT_RENAMED$STATUS"
fi

if $(echo "$git_status" | grep -q '^ D '); then
    STATUS="$ZSH_THEME_SCM_PROMPT_DELETED$STATUS"
fi

if $(echo "$git_status" | grep -q '^UU '); then
    STATUS="$ZSH_THEME_SCM_PROMPT_UNMERGED$STATUS"
fi

echo $STATUS
