#!/usr/bin/env zsh

if [[ ${ZSH_GIT} -eq 0 ]] then
    ZSH_GIT_BRANCH="$(git branch -v 2>/dev/null | grep "^*")"
    ZSH_GIT_STATUS="$(git status --porcelain 2>/dev/null)"

    export ZSH_GIT_INFO_DIRTY="$(git_parse_dirty)"
    export ZSH_GIT_INFO_BRANCH="$ZSH_THEME_SCM_BRANCH_PREFIX$(git_current_branch)$ZSH_THEME_SCM_BRANCH_SUFFIX"
    export ZSH_GIT_INFO_BRANCH_STATUS="$(git_parse_branch_status)"
    export ZSH_GIT_INFO_PATCHES=""
    export ZSH_GIT_INFO_TAGS=""
fi
