#!/usr/bin/env zsh

local git_status=$1
local git_basedir=$2

local status_indicator=""

if $(echo "$git_status" | grep -q '^?? '); then
    zstyle -s ":oh-my-zsh:vcs-info:prompt:git:$git_basedir" untracked status_indicator
fi

if $(echo "$git_status" | grep -q '^A  '); then
    zstyle -s ":oh-my-zsh:vcs-info:prompt:git:$git_basedir" added status_indicator
elif $(echo "$git_status" | grep -q '^M  '); then
    zstyle -s ":oh-my-zsh:vcs-info:prompt:git:$git_basedir" added status_indicator
fi

if $(echo "$git_status" | grep -q '^ M '); then
    zstyle -s ":oh-my-zsh:vcs-info:prompt:git:$git_basedir" modified status_indicator
fi

if $(echo "$git_status" | grep -q '^R  '); then
    zstyle -s ":oh-my-zsh:vcs-info:prompt:git:$git_basedir" renamed status_indicator
fi

if $(echo "$git_status" | grep -q '^ D '); then
    zstyle -s ":oh-my-zsh:vcs-info:prompt:git:$git_basedir" deleted status_indicator
fi

if $(echo "$git_status" | grep -q '^UU '); then
    zstyle -s ":oh-my-zsh:vcs-info:prompt:git:$git_basedir" unmerged status_indicator
fi

print "$status_indicator"
