#!/usr/bin/env zsh

autoload hg_branch_status

# Assume we didn't start in a hg repo
export ZSH_VCS_HG_ON=256

export ZSH_HG_DIRTY_TEMPLATE="<status|modified(${ZSH_THEME_SCM_PROMPT_DIRTY})|unknown(${ZSH_THEME_SCM_PROMPT_UNTRACKED})|clean(${ZSH_THEME_SCM_PROMPT_CLEAN})>"
export ZSH_HG_BRANCH_TEMPLATE="<${ZSH_THEME_SCM_BRANCH_PREFIX}<branch>${ZSH_THEME_SCM_BRANCH_SUFFIX}>"
export ZSH_HG_PATCHES_TEMPLATE="<${ZSH_THEME_SCM_PATCHES_PREFIX}<patches|join(${ZSH_THEME_SCM_PATCHES_SEP})|pre_applied(${ZSH_THEME_PATCHES_PREAPPLIED})|pre_unapplied(${ZSH_THEME_PATHCES_PREUNAPPLIED})|post_applied(${ZSH_THEME_PATCHES_POSTAPPLIED})|post_unapplied(${ZSH_THEME_PATCHES_POSTUNAPPLIED})>${ZSH_THEME_SCM_PATCHES_SUFFIX}>"
export ZSH_HG_TAGS_TEMPLATE="<${ZSH_THEME_SCM_TAGS_PREFIX}<tags|${ZSH_THEME_SCM_TAGS_SEP}>${ZSH_THEME_SCM_TAGS_SUFFIX}>"
