#!/usr/bin/env zsh

cvs_status=$(cvs status 2>/dev/null)

ZSH_CVS_INFO_BRANCH="$ZSH_THEME_SCM_BRANCH_PREFIX$(cvs_parse_current_branch $cvs_status)$ZSH_THEME_SCM_BRANCH_SUFFIX"
ZSH_CVS_INFO_TAG="" #cvs can have too many tags on one checkout, this probably wouldn't be useful
ZSH_CVS_INFO_DIRTY="$(cvs_parse_dirty $cvs_status)"
ZSH_CVS_INFO_BRANCH_STATUS="$(cvs_parse_branch_status $cvs_status)"
ZSH_CVS_INFO_PATCHES=""
ZSH_CVS_INFO_TYPE="$ZSH_THEME_SCM_PROMPT_CVS"
