#!/usr/bin/env zsh

type_var=ZSH_VCS_$1_ON
theme_prompt_var=ZSH_THEME_SCM_PROMPT_$1
dirty_var=ZSH_$1_INFO_DIRTY
branch_var=ZSH_$1_INFO_BRANCH
branch_status_var=ZSH_$1_INFO_BRANCH_STATUS
patches_var=ZSH_$1_INFO_PATCHES
tags_var=ZSH_$1_INFO_TAGS

#if someone else is on, don't print
#note that this means for a dir with multiple vcss, none are shown.
for flag in $(env | grep \$ZSH_VCS_\.\*_ON)
do
    if [[ "${flag}" != "${type_var}" && ${(P)flag} -eq 0 ]] then
        return
    fi
done

if [[ ${(P)type_var} -ne 0 ]] then
    return
fi

if [[ -z $ZSH_SCM_INFO_TYPE ]] then
export ZSH_SCM_INFO_TYPE="${(P)theme_prompt_var}"
fi
if [[ -z $ZSH_SCM_INFO_DIRTY ]] then
export ZSH_SCM_INFO_DIRTY="${(P)dirty_var}"
fi
if [[ -z $ZSH_SCM_INFO_BRANCH ]] then
export ZSH_SCM_INFO_BRANCH="${(P)branch_var}"
fi
if [[ -z $ZSH_SCM_INFO_BRANCH_STATUS ]] then
export ZSH_SCM_INFO_BRANCH_STATUS="${(P)branch_status_var}"
fi
if [[ -z $ZSH_SCM_INFO_PATCHES ]] then
export ZSH_SCM_INFO_PATCHES="${(P)patches_var}"
fi
if [[ -z $ZSH_SCM_INFO_TAGS ]] then
export ZSH_SCM_INFO_TAGS="${(P)tags_var}"
fi

