#!/usr/bin/env zsh

rcs_type=$1
lc_rcs_type=${(L)rcs_type}

type_var=ZSH_VCS_${rcs_type}_ON
dirty_var=ZSH_${rcs_type}_INFO_DIRTY
branch_var=ZSH_${rcs_type}_INFO_BRANCH
branch_status_var=ZSH_${rcs_type}_INFO_BRANCH_STATUS
patches_var=ZSH_${rcs_type}_INFO_PATCHES
tags_var=ZSH_${rcs_type}_INFO_TAGS

#if another plugin is on, don't print
#note that this means for a dir with multiple vcss, none are shown.
for flag in $(env | grep \$ZSH_VCS_\.\*_ON)
do
    if [[ "${flag}" != "${type_var}" && ${(P)flag} -eq 0 ]] then
        return
    fi
done

if [[ ${(P)type_var} -ne 0 ]] then
    return
fi

zstyle -s ":oh-my-zsh:vcs-info:${lc_rcs_type}" format ZSH_SCM_INFO_TYPE 
ZSH_SCM_INFO_DIRTY="${(P)dirty_var}"
ZSH_SCM_INFO_BRANCH="${(P)branch_var}"
ZSH_SCM_INFO_BRANCH_STATUS="${(P)branch_status_var}"
ZSH_SCM_INFO_PATCHES="${(P)patches_var}"
ZSH_SCM_INFO_TAGS="${(P)tags_var}"

