#!/usr/bin/env zsh

local return_code="%(?..%{$fg[red]%} ↵%?%{$reset_color%})"
local running_jobs="%(1j.%{$fg[cyan]%} ⚙%j%{$reset_color%}.)"

PROMPT='%{$fg[magenta]%}%n%{$reset_color%} at %{$fg[yellow]%}%m%{$reset_color%} in %{$fg_bold[green]%}${PWD/#$HOME/~}%{$reset_color%}${ZSH_SCM_INFO_TYPE}${ZSH_SCM_INFO_BRANCH}${ZSH_SCM_INFO_BRANCH_STATUS}${ZSH_SCM_INFO_PATCHES}${ZSH_SCM_INFO_TAGS}${ZSH_SCM_INFO_DIRTY}'"${return_code}${running_jobs}"'
%# '

# :oh-my-zsh:vcs-info:<type>:<basedir>:

zstyle ':oh-my-zsh:vcs-info:prompt:*:*' prefix ""
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' suffix ""
zstyle ':oh-my-zsh:vcs-info:prompt:git:*' type-indicator " git"
zstyle ':oh-my-zsh:vcs-info:prompt:hg:*' type-indicator " hg"
zstyle ':oh-my-zsh:vcs-info:prompt:cvs:*' type-indicator " cvs"
zstyle ':oh-my-zsh:vcs-info:prompt:svn:*' type-indicator " svn"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' branch-format " on %{$fg[magenta]%}%B%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' tags-format " at %{$fg[yellow]%}%T%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' tags-separator ", "
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' tag-format "%{$fg[yellow]%}%t%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' patches-format " %{$fg[yellow]%}%P%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' patches-separator "→"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' patch-unapplied-format "%{$fg[yellow]%}%p%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' patch-applied-format "%{$fg_bold[black]%}%p%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' dirty "%{$fg[green]%}!%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' untracked "%{$fg[green]%}?%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' renamed "%{$fg[green]%}R%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' modified "%{$fg[green]%}!%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' unmerged "%{$fg[green]%}U%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' deleted "%{$fg[green]%}D%{$reset_color%}"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' clean ""
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' ahead "↑"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' diverged "↕"
zstyle ':oh-my-zsh:vcs-info:prompt:*:*' behind "↓"
